/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as RedditSignalsRouteImport } from './routes/reddit-signals'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as LiveRouteImport } from './routes/live'
import { Route as IoDataRouteImport } from './routes/io-data'
import { Route as ApiHealthRouteImport } from './routes/api-health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeTickerRouteImport } from './routes/trade.$ticker'
import { Route as ApiProvidersPublicStatusRouteImport } from './routes/api/providers/public.status'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RedditSignalsRoute = RedditSignalsRouteImport.update({
  id: '/reddit-signals',
  path: '/reddit-signals',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const IoDataRoute = IoDataRouteImport.update({
  id: '/io-data',
  path: '/io-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api-health',
  path: '/api-health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeTickerRoute = TradeTickerRouteImport.update({
  id: '/trade/$ticker',
  path: '/trade/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProvidersPublicStatusRoute =
  ApiProvidersPublicStatusRouteImport.update({
    id: '/api/providers/public/status',
    path: '/api/providers/public/status',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-health': typeof ApiHealthRoute
  '/io-data': typeof IoDataRoute
  '/live': typeof LiveRoute
  '/patterns': typeof PatternsRoute
  '/performance': typeof PerformanceRoute
  '/reddit-signals': typeof RedditSignalsRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/trade/$ticker': typeof TradeTickerRoute
  '/api/providers/public/status': typeof ApiProvidersPublicStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-health': typeof ApiHealthRoute
  '/io-data': typeof IoDataRoute
  '/live': typeof LiveRoute
  '/patterns': typeof PatternsRoute
  '/performance': typeof PerformanceRoute
  '/reddit-signals': typeof RedditSignalsRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/trade/$ticker': typeof TradeTickerRoute
  '/api/providers/public/status': typeof ApiProvidersPublicStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-health': typeof ApiHealthRoute
  '/io-data': typeof IoDataRoute
  '/live': typeof LiveRoute
  '/patterns': typeof PatternsRoute
  '/performance': typeof PerformanceRoute
  '/reddit-signals': typeof RedditSignalsRoute
  '/scanner': typeof ScannerRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/trade/$ticker': typeof TradeTickerRoute
  '/api/providers/public/status': typeof ApiProvidersPublicStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-health'
    | '/io-data'
    | '/live'
    | '/patterns'
    | '/performance'
    | '/reddit-signals'
    | '/scanner'
    | '/settings'
    | '/watchlist'
    | '/trade/$ticker'
    | '/api/providers/public/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-health'
    | '/io-data'
    | '/live'
    | '/patterns'
    | '/performance'
    | '/reddit-signals'
    | '/scanner'
    | '/settings'
    | '/watchlist'
    | '/trade/$ticker'
    | '/api/providers/public/status'
  id:
    | '__root__'
    | '/'
    | '/api-health'
    | '/io-data'
    | '/live'
    | '/patterns'
    | '/performance'
    | '/reddit-signals'
    | '/scanner'
    | '/settings'
    | '/watchlist'
    | '/trade/$ticker'
    | '/api/providers/public/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  IoDataRoute: typeof IoDataRoute
  LiveRoute: typeof LiveRoute
  PatternsRoute: typeof PatternsRoute
  PerformanceRoute: typeof PerformanceRoute
  RedditSignalsRoute: typeof RedditSignalsRoute
  ScannerRoute: typeof ScannerRoute
  SettingsRoute: typeof SettingsRoute
  WatchlistRoute: typeof WatchlistRoute
  TradeTickerRoute: typeof TradeTickerRoute
  ApiProvidersPublicStatusRoute: typeof ApiProvidersPublicStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reddit-signals': {
      id: '/reddit-signals'
      path: '/reddit-signals'
      fullPath: '/reddit-signals'
      preLoaderRoute: typeof RedditSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/io-data': {
      id: '/io-data'
      path: '/io-data'
      fullPath: '/io-data'
      preLoaderRoute: typeof IoDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-health': {
      id: '/api-health'
      path: '/api-health'
      fullPath: '/api-health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$ticker': {
      id: '/trade/$ticker'
      path: '/trade/$ticker'
      fullPath: '/trade/$ticker'
      preLoaderRoute: typeof TradeTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/providers/public/status': {
      id: '/api/providers/public/status'
      path: '/api/providers/public/status'
      fullPath: '/api/providers/public/status'
      preLoaderRoute: typeof ApiProvidersPublicStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  IoDataRoute: IoDataRoute,
  LiveRoute: LiveRoute,
  PatternsRoute: PatternsRoute,
  PerformanceRoute: PerformanceRoute,
  RedditSignalsRoute: RedditSignalsRoute,
  ScannerRoute: ScannerRoute,
  SettingsRoute: SettingsRoute,
  WatchlistRoute: WatchlistRoute,
  TradeTickerRoute: TradeTickerRoute,
  ApiProvidersPublicStatusRoute: ApiProvidersPublicStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
